[package]
name = "stm-probers"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.157", features = ["derive"] }
serde_yaml = "0.9.19"
quick-xml = { version = "0.31.0", features = [] }
stm32-data-gen = { git = "https://github.com/bugadani/stm32-data.git", branch = "lib" }
stm32-data-serde = { git = "https://github.com/bugadani/stm32-data.git", branch = "lib" }
probe-rs-target = { git = "https://github.com/probe-rs/probe-rs.git", rev = "a0b2fb35b441d27862ec877f0a3ef25114986840" }
target-gen = { git = "https://github.com/probe-rs/probe-rs.git", rev = "a0b2fb35b441d27862ec877f0a3ef25114986840" }
